"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { HeroState } from "@/components/hero-state"
import { TripGallery } from "@/components/trip-gallery"
import { useBotpressBrain } from "@/hooks/useBotpressBrain"
import { useCreateTrip, useListTrips, useDeleteTrip } from "@/hooks/useTrip"
import { mapBotpressToTripData, isValidTripData, extractTripJson } from "@/lib/trip-utils"
import type { TripData } from "@/lib/trip-types"
import type { TripState } from "@/types/trip"

export function HomePage() {
  const router = useRouter()
  const createTripMutation = useCreateTrip()
  const deleteTripMutation = useDeleteTrip()
  const savedTrips = useListTrips()
  const { sendToBrain } = useBotpressBrain()
  
  const [isSubmitting, setIsSubmitting] = useState(false)

  const handleTripSubmit = async (prompt: string) => {
    if (isSubmitting) {
      console.warn('[Trip Submit] Already submitting, ignoring duplicate call')
      return
    }
    
    setIsSubmitting(true)
    const timestamp = () => new Date().toLocaleTimeString()
    console.log(`[${timestamp()}] Processing request: "${prompt}"`)

    try {
      // Call Botpress
      const response = await sendToBrain(prompt)
      let finalTripData: TripData | null = null

      if (response) {
        const tripJson = extractTripJson(response)
        if (tripJson) {
          const mappedData = mapBotpressToTripData(tripJson)
          if (mappedData && isValidTripData(mappedData)) {
            finalTripData = mappedData
          }
        }
      }

      if (finalTripData) {
        // Create trip in Convex
        const tripId = await createTripMutation({
          destination: finalTripData.destination,
          title: `${finalTripData.duration} in ${finalTripData.destination}`,
          summary: `Exploration of ${finalTripData.destination} generated by Trip OS`,
          days: finalTripData.days,
          budget: {
            total: finalTripData.totalBudget,
            spent: 0,
            breakdown: { food: 0, activity: 0, travel: 0 },
            currency: "USD"
          }
        })
        
        // Navigate to the new trip page
        router.push(`/trip/${tripId}`)
      } else {
        console.error('Failed to generate valid trip data')
        setIsSubmitting(false)
      }
    } catch (error) {
      console.error('[Botpress Error]', error)
      setIsSubmitting(false)
    }
  }

  const handleSelectTrip = (trip: TripState) => {
    router.push(`/trip/${trip.id}`)
  }

  const handleDeleteTrip = async (tripId: string) => {
    try {
      await deleteTripMutation({ tripId: tripId as any })
    } catch (error) {
      console.error('Failed to delete trip:', error)
    }
  }

  return (
    <div className="relative min-h-screen bg-neutral-950 overflow-hidden text-white overflow-y-auto scrollbar-hide">
      <div className="fixed inset-0 bg-[radial-gradient(ellipse_80%_50%_at_50%_-20%,rgba(120,119,198,0.15),transparent)]" />
      <div className="fixed top-0 left-1/4 w-96 h-96 bg-white/2 rounded-full blur-3xl" />
      <div className="fixed bottom-0 right-1/4 w-96 h-96 bg-white/2 rounded-full blur-3xl" />

      <HeroState onSubmit={handleTripSubmit} />
      
      {savedTrips && savedTrips.length > 0 && (
        <div className="pb-20 relative z-20">
          <TripGallery 
            trips={savedTrips} 
            onSelectTrip={handleSelectTrip} 
            onDeleteTrip={handleDeleteTrip}
            onCreateNew={() => {
              window.scrollTo({ top: 0, behavior: 'smooth' })
            }} 
          />
        </div>
      )}
    </div>
  )
}
